import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { Provider } from "@/components/ui/provider";
import Navbar from "@/components/Navbar";
import TimeCard from "@/components/TimeCard";
import Footer from "@/components/Footer";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			lang='en'
			suppressHydrationWarning
		>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<Provider>
					<div className='flex md:flex-row flex-col justify-between p-4'>
						<div className='text-white bg-emerald-600 rounded-md shadow-2xl p-2 font-semibold text-4xl flex items-center italic -skew-x-6 md:mb-0 mb-4'>
							WebResume
						</div>
						<TimeCard />
					</div>
					<Navbar />
					{children}
					<Footer />
				</Provider>
			</body>
		</html>
	);
}
